language: java
jdk:
  - openjdk8
services:
  - docker
  -
jobs:
  include:
    - script:
        # Show Java version
        - java -version

        # Show Maven version
        - mvn --version

        - mvn clean install

      name: "Native Image compile on Travis Host"

    - script:
        # Login into Heroku Container Registry first, so that we can push our Image later
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.heroku.com

        # Compile App with Docker
        - docker build . --tag=registry.heroku.com/qrcode-spring/web

        # Push to Heroku Container Registry
        - docker push registry.heroku.com/qrcode-spring/web

        # Release Dockerized Native Spring Boot App on Heroku
        - ./heroku-release.sh qrcode-spring

        # Push to Docker Hub also, since automatic Builds there don't have anough RAM to do a docker build
        - echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        - docker tag registry.heroku.com/qrcode-spring/web giskardocker80/qrcode-spring:latest
        - docker push giskardocker80/qrcode-spring:latest

      name: "Native Image compile in Docker on Travis & Push to Heroku Container Registry"