language: java
jdk:
  - openjdk8
services:
  - docker
addons:
  sonarcloud:
    organization: "giskardb"
    token:
      secure: $SONAR_TOKEN
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
jobs:
  include:
    - script:
        # Show Java version
        - java -version

        # Show Maven version
        - mvn --version

        # Compile spring boot app
        - mvn clean install

      name: "Compile spring app project on Travis Host"

    - script:
        # Login into Heroku Container Registry first, so that we can push our Image later
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.heroku.com

        # Compile App with Docker
        - docker build . --tag=registry.heroku.com/qrcode-spring/web

        # Push to Heroku Container Registry
        - docker push registry.heroku.com/qrcode-spring/web

        # Release Dockerized Native Spring Boot App on Heroku
        - chmod +x heroku-release.sh && ./heroku-release.sh qrcode-spring

        # Push to Docker Hub also
        - echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        - docker tag registry.heroku.com/qrcode-spring/web giskardocker80/qrcode-spring:latest
        - docker push giskardocker80/qrcode-spring:latest

      name: "Docker Image compile on Travis & Push to Heroku Container Registry and Docker Hub"